# Nombre del proyecto
sonar.projectKey=gym-flow-back-movile-platform-ms

# Nombre visible del proyecto
sonar.projectName=gym-flow-back-movile-platform-ms

sonar.host.url=https://sonarcloud.io

# Versión del proyecto
sonar.projectVersion=1.0

# Ruta de los archivos de configuración de NestJS
sonar.inclusions=**/*.service.ts,**/*.usecase.ts,**/*.controller.ts,**/*.adapter.ts,**/*.interceptor.(t|j)s
sonar.coverage.exclusions=**/*spec.ts
sonar.cpd.exclusions=**/*spec.ts,**/*controller.ts
javascript.ruleKey=S6480

# Otras configuraciones de SonarQube según sea necesario
sonar.javascript.lcov.reportPaths=./coverage/lcov.info