name: CD

on:
  push:
    branches:
      - dev
      - test
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "TAG=dev-latest" >> $GITHUB_ENV
            echo "WEBHOOK=${{ secrets.DOCKPLOY_WEBHOOK_DEV }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
            echo "TAG=test-latest" >> $GITHUB_ENV
            echo "WEBHOOK=${{ secrets.DOCKPLOY_WEBHOOK_TEST }}" >> $GITHUB_ENV
          else
            echo "TAG=prod-latest" >> $GITHUB_ENV
            echo "WEBHOOK=${{ secrets.DOCKPLOY_WEBHOOK_PROD }}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gym-flow-back-movile-platform-ms:${TAG} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gym-flow-back-movile-platform-ms:${TAG}

      - name: Trigger Dockploy deploy
        run: |
          curl -X POST $WEBHOOK